baseURL = 'https://thecoup.xyz/'
languageCode = 'en-us'
title = 'TheCoup.xyz'
theme = 'default'

[markup.goldmark.renderer]
  # This allows raw HTML (like <p> tags) to be rendered in the feed.
  # This is essential for your <description> tag.
  unsafe = true

[markup.goldmark.extensions]
  # This disables the feature that converts ' to &rsquo; etc.
  typographer = false

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    name = "Essays"
    url = "/essays/"
    weight = 30
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 40
  [[menu.main]]
    name = "Portfolio"
    # This now links to your professional site
    url = "https://pro.thecoup.xyz/"
    weight = 50
  [[menu.main]]
    name = "Slashes"
    url = "/slashes/"
    weight = 60