baseURL = 'https://thecoup.xyz/'
languageCode = 'en-us'
title = 'TheCoup.xyz'
theme = 'default' # The name of your theme folder

[markup.goldmark.renderer]
unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Blog"
    url = "/posts/" # This should match your blog content folder
    weight = 20
  [[menu.main]]
    name = "Essays"
    url = "/essays/"
    weight = 30
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 40
  [[menu.main]]
    name = "Portfolio"
    # This now links to your professional site
    url = "https://pro.thecoup.xyz/"
    weight = 50
  [[menu.main]]
    name = "Slashes"
    url = "/slashes/"
    weight = 60